/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author allan
 */
public class Aplication extends javax.swing.JFrame {

    /**
     * Creates new form Aplication
     */
    public Aplication() {
        
       
        initComponents();
        btnLast = null;
        capsFlag = false;
    }
    private Color cinza = Color.GRAY;
    private JButton btnLast;
    private Color capsAux;
    private boolean capsFlag;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        pangrama = new javax.swing.JLabel();
        descricao = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        aspasBtn = new javax.swing.JButton();
        tBtn = new javax.swing.JButton();
        pontoBtn = new javax.swing.JButton();
        quatroBtn = new javax.swing.JButton();
        seteBtn = new javax.swing.JButton();
        eBtn = new javax.swing.JButton();
        downBtn = new javax.swing.JButton();
        zeroBtn = new javax.swing.JButton();
        uBtn = new javax.swing.JButton();
        aBtn = new javax.swing.JButton();
        rBtn = new javax.swing.JButton();
        oBtn = new javax.swing.JButton();
        maisBtn = new javax.swing.JButton();
        hBtn = new javax.swing.JButton();
        upBtn = new javax.swing.JButton();
        doisBtn = new javax.swing.JButton();
        pontVirgBtn = new javax.swing.JButton();
        tabBtn = new javax.swing.JButton();
        seisBtn = new javax.swing.JButton();
        concRightBtn = new javax.swing.JButton();
        barraBtn = new javax.swing.JButton();
        bBtn = new javax.swing.JButton();
        iBtn = new javax.swing.JButton();
        fBtn = new javax.swing.JButton();
        enterBtn = new javax.swing.JButton();
        noveBtn = new javax.swing.JButton();
        gBtn = new javax.swing.JButton();
        zBtn = new javax.swing.JButton();
        cBtn = new javax.swing.JButton();
        cdilhaBtn = new javax.swing.JButton();
        qBtn = new javax.swing.JButton();
        umBtn = new javax.swing.JButton();
        nBtn = new javax.swing.JButton();
        shiftBtn = new javax.swing.JButton();
        wBtn = new javax.swing.JButton();
        oitoBtn = new javax.swing.JButton();
        menosBtn = new javax.swing.JButton();
        lbtn = new javax.swing.JButton();
        capsBtn = new javax.swing.JButton();
        sBtn = new javax.swing.JButton();
        rightBtn = new javax.swing.JButton();
        leftBtn = new javax.swing.JButton();
        virgBtn = new javax.swing.JButton();
        kbtn = new javax.swing.JButton();
        pBtn = new javax.swing.JButton();
        backspcBtn = new javax.swing.JButton();
        xBtn = new javax.swing.JButton();
        jBtn = new javax.swing.JButton();
        spaceBtn = new javax.swing.JButton();
        concLeftBtn = new javax.swing.JButton();
        vBtn = new javax.swing.JButton();
        mBtn = new javax.swing.JButton();
        yBtn = new javax.swing.JButton();
        dBtn = new javax.swing.JButton();
        tresBtn = new javax.swing.JButton();
        cincoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textArea.setColumns(20);
        textArea.setRows(5);
        textArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textAreaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textAreaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textAreaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(textArea);

        pangrama.setText("Mensagem pangrama");

        descricao.setText("descricao");

        aspasBtn.setText("'");
        aspasBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        aspasBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        aspasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aspasBtnActionPerformed(evt);
            }
        });
        aspasBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aspasBtnKeyPressed(evt);
            }
        });

        tBtn.setText("T");
        tBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        tBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        tBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtnActionPerformed(evt);
            }
        });

        pontoBtn.setText(".");
        pontoBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        pontoBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        pontoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pontoBtnActionPerformed(evt);
            }
        });

        quatroBtn.setText("4");
        quatroBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        quatroBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        quatroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quatroBtnActionPerformed(evt);
            }
        });

        seteBtn.setText("7");
        seteBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        seteBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        seteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seteBtnActionPerformed(evt);
            }
        });

        eBtn.setText("E");
        eBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        eBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        eBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBtnActionPerformed(evt);
            }
        });

        downBtn.setText("↓");
        downBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        downBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        downBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downBtnActionPerformed(evt);
            }
        });

        zeroBtn.setText("0");
        zeroBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        zeroBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        zeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroBtnActionPerformed(evt);
            }
        });

        uBtn.setText("U");
        uBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        uBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        uBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uBtnActionPerformed(evt);
            }
        });

        aBtn.setText("A");
        aBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        aBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        aBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBtnActionPerformed(evt);
            }
        });

        rBtn.setText("R");
        rBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        rBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        rBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnActionPerformed(evt);
            }
        });

        oBtn.setText("O");
        oBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        oBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        oBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oBtnActionPerformed(evt);
            }
        });

        maisBtn.setText("+");
        maisBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        maisBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        maisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maisBtnActionPerformed(evt);
            }
        });

        hBtn.setText("H");
        hBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        hBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        hBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hBtnActionPerformed(evt);
            }
        });

        upBtn.setText("↑");
        upBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        upBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        upBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upBtnActionPerformed(evt);
            }
        });

        doisBtn.setText("2");
        doisBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        doisBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        doisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doisBtnActionPerformed(evt);
            }
        });

        pontVirgBtn.setText(";");
        pontVirgBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        pontVirgBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        pontVirgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pontVirgBtnActionPerformed(evt);
            }
        });

        tabBtn.setText("TAB");
        tabBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        tabBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        tabBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabBtnActionPerformed(evt);
            }
        });

        seisBtn.setText("6");
        seisBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        seisBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        seisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisBtnActionPerformed(evt);
            }
        });

        concRightBtn.setText("]");
        concRightBtn.setMaximumSize(new java.awt.Dimension(48, 48));
        concRightBtn.setMinimumSize(new java.awt.Dimension(48, 48));
        concRightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concRightBtnActionPerformed(evt);
            }
        });

        barraBtn.setText("\\");
            barraBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            barraBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            barraBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    barraBtnActionPerformed(evt);
                }
            });

            bBtn.setText("B");
            bBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            bBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            bBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bBtnActionPerformed(evt);
                }
            });

            iBtn.setText("I");
            iBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            iBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            iBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    iBtnActionPerformed(evt);
                }
            });

            fBtn.setText("F");
            fBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            fBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            fBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    fBtnActionPerformed(evt);
                }
            });

            enterBtn.setText("ENTER");
            enterBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            enterBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            enterBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    enterBtnActionPerformed(evt);
                }
            });

            noveBtn.setText("9");
            noveBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            noveBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            noveBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    noveBtnActionPerformed(evt);
                }
            });

            gBtn.setText("G");
            gBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            gBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            gBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    gBtnActionPerformed(evt);
                }
            });

            zBtn.setText("Z");
            zBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            zBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            zBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    zBtnActionPerformed(evt);
                }
            });

            cBtn.setText("C");
            cBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            cBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            cBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cBtnActionPerformed(evt);
                }
            });

            cdilhaBtn.setText("Ç");
            cdilhaBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            cdilhaBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            cdilhaBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cdilhaBtnActionPerformed(evt);
                }
            });

            qBtn.setText("Q");
            qBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            qBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            qBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    qBtnActionPerformed(evt);
                }
            });

            umBtn.setText("1");
            umBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            umBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            umBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    umBtnActionPerformed(evt);
                }
            });

            nBtn.setText("N");
            nBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            nBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            nBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    nBtnActionPerformed(evt);
                }
            });

            shiftBtn.setText("SHIFT");
            shiftBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            shiftBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            shiftBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    shiftBtnActionPerformed(evt);
                }
            });

            wBtn.setText("W");
            wBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            wBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            wBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    wBtnActionPerformed(evt);
                }
            });

            oitoBtn.setText("8");
            oitoBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            oitoBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            oitoBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    oitoBtnActionPerformed(evt);
                }
            });

            menosBtn.setText("-");
            menosBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            menosBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            menosBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    menosBtnActionPerformed(evt);
                }
            });

            lbtn.setText("L");
            lbtn.setMaximumSize(new java.awt.Dimension(48, 48));
            lbtn.setMinimumSize(new java.awt.Dimension(48, 48));
            lbtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    lbtnActionPerformed(evt);
                }
            });

            capsBtn.setText("CAPSLOCK");
            capsBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            capsBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            capsBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    capsBtnActionPerformed(evt);
                }
            });

            sBtn.setText("S");
            sBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            sBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            sBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    sBtnActionPerformed(evt);
                }
            });

            rightBtn.setText("→");
            rightBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            rightBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            rightBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    rightBtnActionPerformed(evt);
                }
            });

            leftBtn.setText("←");
            leftBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            leftBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            leftBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    leftBtnActionPerformed(evt);
                }
            });

            virgBtn.setText(",");
            virgBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            virgBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            virgBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    virgBtnActionPerformed(evt);
                }
            });

            kbtn.setText("K");
            kbtn.setMaximumSize(new java.awt.Dimension(48, 48));
            kbtn.setMinimumSize(new java.awt.Dimension(48, 48));
            kbtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    kbtnActionPerformed(evt);
                }
            });

            pBtn.setText("P");
            pBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            pBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            pBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    pBtnActionPerformed(evt);
                }
            });

            backspcBtn.setText("Backspace");

            xBtn.setText("X");
            xBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            xBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            xBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    xBtnActionPerformed(evt);
                }
            });

            jBtn.setText("J");
            jBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            jBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            jBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jBtnActionPerformed(evt);
                }
            });

            spaceBtn.setText("SPACE");
            spaceBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            spaceBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            spaceBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    spaceBtnActionPerformed(evt);
                }
            });

            concLeftBtn.setText("[");
            concLeftBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            concLeftBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            concLeftBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    concLeftBtnActionPerformed(evt);
                }
            });

            vBtn.setText("V");
            vBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            vBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            vBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    vBtnActionPerformed(evt);
                }
            });

            mBtn.setText("M");
            mBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            mBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            mBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    mBtnActionPerformed(evt);
                }
            });

            yBtn.setText("Y");
            yBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            yBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            yBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    yBtnActionPerformed(evt);
                }
            });

            dBtn.setText("D");
            dBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            dBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            dBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    dBtnActionPerformed(evt);
                }
            });

            tresBtn.setText("3");
            tresBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            tresBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            tresBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    tresBtnActionPerformed(evt);
                }
            });

            cincoBtn.setText("5");
            cincoBtn.setMaximumSize(new java.awt.Dimension(48, 48));
            cincoBtn.setMinimumSize(new java.awt.Dimension(48, 48));
            cincoBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cincoBtnActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(aspasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(umBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(doisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(tresBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(quatroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(cincoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(seisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(seteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(oitoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(noveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(zeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(menosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(maisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(backspcBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tabBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(qBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(wBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(eBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(rBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(tBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(yBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(uBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(iBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(oBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(pBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(concLeftBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enterBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(capsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(aBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(sBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(dBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(fBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(gBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(hBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(kbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(lbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(cdilhaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(concRightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(shiftBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(barraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(zBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(xBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(cBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(vBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(bBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(nBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(mBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(virgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(pontoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(190, 190, 190)
                                    .addComponent(spaceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(pontVirgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(leftBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(downBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(upBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(2, 2, 2)
                            .addComponent(rightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aspasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(umBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tresBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quatroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cincoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oitoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maisBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(backspcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(concLeftBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(enterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(iBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(uBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tabBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(capsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(aBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cdilhaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(concRightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(shiftBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(barraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(zBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(xBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(vBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(virgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pontoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pontVirgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(upBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(8, 8, 8)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spaceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(downBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(leftBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                        .addComponent(pangrama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(pangrama)
                    .addGap(15, 15, 15)
                    .addComponent(descricao)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26))
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void aspasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aspasBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aspasBtnActionPerformed

    private void umBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_umBtnActionPerformed

    private void doisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doisBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doisBtnActionPerformed

    private void tresBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tresBtnActionPerformed

    private void quatroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quatroBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quatroBtnActionPerformed

    private void cincoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cincoBtnActionPerformed

    private void seisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seisBtnActionPerformed

    private void seteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seteBtnActionPerformed

    private void oitoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oitoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oitoBtnActionPerformed

    private void noveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noveBtnActionPerformed

    private void zeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zeroBtnActionPerformed

    private void menosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menosBtnActionPerformed

    private void maisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maisBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maisBtnActionPerformed

    private void concLeftBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concLeftBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_concLeftBtnActionPerformed

    private void pBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pBtnActionPerformed

    private void oBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oBtnActionPerformed

    private void iBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iBtnActionPerformed

    private void uBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uBtnActionPerformed

    private void tBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tBtnActionPerformed

    private void yBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yBtnActionPerformed

    private void rBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnActionPerformed

    private void wBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wBtnActionPerformed

    private void eBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eBtnActionPerformed

    private void tabBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabBtnActionPerformed

    private void qBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qBtnActionPerformed

    private void enterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterBtnActionPerformed

    private void capsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capsBtnActionPerformed

    private void fBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fBtnActionPerformed

    private void aBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aBtnActionPerformed

    private void sBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sBtnActionPerformed

    private void dBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dBtnActionPerformed

    private void gBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gBtnActionPerformed

    private void hBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hBtnActionPerformed

    private void jBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnActionPerformed

    private void kbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kbtnActionPerformed

    private void lbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbtnActionPerformed

    private void cdilhaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdilhaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cdilhaBtnActionPerformed

    private void concRightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concRightBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_concRightBtnActionPerformed

    private void shiftBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shiftBtnActionPerformed

    private void barraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraBtnActionPerformed

    private void zBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zBtnActionPerformed

    private void xBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xBtnActionPerformed

    private void cBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBtnActionPerformed

    private void vBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vBtnActionPerformed

    private void bBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bBtnActionPerformed

    private void nBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nBtnActionPerformed

    private void mBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mBtnActionPerformed

    private void virgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virgBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_virgBtnActionPerformed

    private void pontoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pontoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pontoBtnActionPerformed

    private void pontVirgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pontVirgBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pontVirgBtnActionPerformed

    private void spaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaceBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spaceBtnActionPerformed

    private void upBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upBtnActionPerformed

    private void downBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downBtnActionPerformed

    private void leftBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leftBtnActionPerformed

    private void rightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightBtnActionPerformed

    private void aspasBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aspasBtnKeyPressed
      
    }//GEN-LAST:event_aspasBtnKeyPressed

    private void textAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAreaKeyPressed
        trocaFundo(verificaTeclaInput(evt.getKeyChar(), evt.getKeyCode()));
        
    }//GEN-LAST:event_textAreaKeyPressed

    private void textAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAreaKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textAreaKeyReleased

    private void textAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textAreaKeyTyped
        
    }//GEN-LAST:event_textAreaKeyTyped
      
    private JButton verificaTeclaInput(char letra,int button){
        switch (button){
            case KeyEvent.VK_QUOTE:
                return aspasBtn;
            case KeyEvent.VK_BACKSPACE:
                return backspcBtn;
            case KeyEvent.VK_TAB:
                return tabBtn;
            case KeyEvent.VK_ENTER:
                return enterBtn;
            case KeyEvent.VK_CAPS_LOCK:
                return capsBtn;
            case KeyEvent.VK_SHIFT:
                return shiftBtn;
            case KeyEvent.VK_BACK_SLASH:
                return barraBtn;
            case KeyEvent.VK_UP:
                return upBtn;
            case KeyEvent.VK_DOWN:
                return downBtn;
            case KeyEvent.VK_LEFT:
                return leftBtn;
            case KeyEvent.VK_RIGHT:
                return rightBtn;
            default:
                switch (letra){
                    case '0':
                        return zeroBtn;
                    case '1':
                        return umBtn;
                    case '2':
                        return doisBtn;
                    case '3':
                        return tresBtn;
                    case '4':
                        return quatroBtn;
                    case '5':
                        return cincoBtn;
                    case '6':
                        return seisBtn;
                    case '7':
                        return seteBtn;
                    case '8':
                        return oitoBtn;
                    case '9':
                        return noveBtn;
                    case '-':
                        return menosBtn;
                    case '+':
                        return maisBtn;
                    case 'q':
                        return qBtn;
                    case 'Q':
                        return qBtn;
                    case 'w':
                        return wBtn;
                    case 'W':
                        return wBtn;
                    case 'e':
                        return eBtn;
                    case 'E':
                        return eBtn;
                    case 'r':
                        return rBtn;
                    case 'R':
                        return rBtn;
                    case 't':
                        return tBtn;
                    case 'T':
                        return tBtn;
                    case 'y':
                        return yBtn;
                    case 'Y':
                        return yBtn;
                    case 'u':
                        return uBtn;
                    case 'U':
                        return uBtn;
                    case 'i':
                        return iBtn;
                    case 'I':
                        return iBtn;
                    case 'o':
                        return oBtn;
                    case 'O':
                        return oBtn;
                    case 'p':
                        return pBtn;
                    case 'P':
                        return pBtn;
                    case '[':
                        return concLeftBtn;
                    case 'a':
                        return aBtn;
                    case 'A':
                        return aBtn;
                    case 's':
                        return sBtn;
                    case 'S':
                        return sBtn;
                    case 'd':
                        return dBtn;
                    case 'D':
                        return dBtn;
                    case 'f':
                        return fBtn;
                    case 'F':
                        return fBtn;
                    case 'g':
                        return gBtn;
                    case 'G':
                        return gBtn;
                    case 'h':
                        return hBtn;
                    case 'H':
                        return hBtn;
                    case 'j':
                        return jBtn;
                    case 'J':
                        return jBtn;
                    case 'k':
                        return kbtn;
                    case 'K':
                        return kbtn;
                    case 'l':
                        return lbtn;
                    case 'L':
                        return lbtn;
                    case 'ç':
                        return cdilhaBtn;
                    case 'Ç':
                        return cdilhaBtn;
                    case ']':
                        return concRightBtn;
                    case 'z':
                        return zBtn;
                    case 'Z':
                        return zBtn;
                    case 'x':
                        return xBtn;
                    case 'X':
                        return xBtn;
                    case 'c':
                        return cBtn;
                    case 'C':
                        return cBtn;
                    case 'v':
                        return vBtn;
                    case 'V':
                        return vBtn;
                    case 'b':
                        return bBtn;
                    case 'B':
                        return bBtn;
                    case 'n':
                        return nBtn;
                    case 'N':
                        return nBtn;
                    case 'm':
                        return mBtn;
                    case 'M':
                        return mBtn;
                    case ',':
                        return virgBtn;
                    case '.':
                        return pontoBtn;
                    case ';':
                        return pontVirgBtn;
                    case ' ':
                        return spaceBtn;

                
                }                
        } 
        return null;
    }
    private void trocaFundo(JButton btn){
        if(btn == null)
            return;
        
        if(btn == capsBtn){
            if(capsFlag){
                capsFlag=false;
                btn.setBackground(capsAux);
            }else{
                capsFlag = true;
                capsAux = btn.getBackground(); 
                btn.setBackground(cinza);
            }
            return;
        }
        if(btnLast == null){
            btnLast = btn;
            btn.setBackground(cinza);
        }else{
            
            btnLast.setBackground(btn.getBackground());
            btnLast = btn;
            btn.setBackground(cinza);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aBtn;
    private javax.swing.JButton aspasBtn;
    private javax.swing.JButton bBtn;
    private javax.swing.JButton backspcBtn;
    private javax.swing.JButton barraBtn;
    private javax.swing.JButton cBtn;
    private javax.swing.JButton capsBtn;
    private javax.swing.JButton cdilhaBtn;
    private javax.swing.JButton cincoBtn;
    private javax.swing.JButton concLeftBtn;
    private javax.swing.JButton concRightBtn;
    private javax.swing.JButton dBtn;
    private javax.swing.JLabel descricao;
    private javax.swing.JButton doisBtn;
    private javax.swing.JButton downBtn;
    private javax.swing.JButton eBtn;
    private javax.swing.JButton enterBtn;
    private javax.swing.JButton fBtn;
    private javax.swing.JButton gBtn;
    private javax.swing.JButton hBtn;
    private javax.swing.JButton iBtn;
    private javax.swing.JButton jBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kbtn;
    private javax.swing.JButton lbtn;
    private javax.swing.JButton leftBtn;
    private javax.swing.JButton mBtn;
    private javax.swing.JButton maisBtn;
    private javax.swing.JButton menosBtn;
    private javax.swing.JButton nBtn;
    private javax.swing.JButton noveBtn;
    private javax.swing.JButton oBtn;
    private javax.swing.JButton oitoBtn;
    private javax.swing.JButton pBtn;
    private javax.swing.JLabel pangrama;
    private javax.swing.JButton pontVirgBtn;
    private javax.swing.JButton pontoBtn;
    private javax.swing.JButton qBtn;
    private javax.swing.JButton quatroBtn;
    private javax.swing.JButton rBtn;
    private javax.swing.JButton rightBtn;
    private javax.swing.JButton sBtn;
    private javax.swing.JButton seisBtn;
    private javax.swing.JButton seteBtn;
    private javax.swing.JButton shiftBtn;
    private javax.swing.JButton spaceBtn;
    private javax.swing.JButton tBtn;
    private javax.swing.JButton tabBtn;
    private javax.swing.JTextArea textArea;
    private javax.swing.JButton tresBtn;
    private javax.swing.JButton uBtn;
    private javax.swing.JButton umBtn;
    private javax.swing.JButton upBtn;
    private javax.swing.JButton vBtn;
    private javax.swing.JButton virgBtn;
    private javax.swing.JButton wBtn;
    private javax.swing.JButton xBtn;
    private javax.swing.JButton yBtn;
    private javax.swing.JButton zBtn;
    private javax.swing.JButton zeroBtn;
    // End of variables declaration//GEN-END:variables
}
